# Generated by Django 4.0.1 on 2022-01-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_title', models.CharField(max_length=200)),
                ('homework_description', models.TextField(max_length=200)),
                ('homework_instruction', models.TextField()),
                ('homework_due_date', models.DateField(null=True)),
                ('homework_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('homework_updated_datetime', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_title', models.CharField(max_length=200)),
                ('content_description', models.CharField(max_length=200)),
                ('content_created_datetime', models.DateTimeField(auto_now_add=True)),
                ('content_updated_datetime', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
