# Generated by Django 4.0.1 on 2022-02-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_homework_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='course_name',
        ),
    ]
